---
title: "MOT_sim_test3"
author: "Kaiwen Lai"
date: "05/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(stringdist)
library(xlsx)
library(openxlsx)
library(reshape2)

library(Hmisc)
```

```{r}
load("sim_rdata_10-5")
```

```{r}
row_big_dt <- dim(big_dt)[1]

sub.dt2b <- big_dt %>% select(make, model, submodel,body_type,transmission_type) %>% mutate_all(list(~tolower(.)))

sub.dt2b$model <- gsub('[-|" "]',"",sub.dt2b$model)

sub.dt2b[sub.dt2b$body_type=="light van" | sub.dt2b$body_type=="heavy van","body_type"] <- "van"
sub.dt2b[sub.dt2b$body_type=="utility","body_type"] <- "ute"
sub.dt2b[sub.dt2b$body_type=="saloon","body_type"] <- "sedan"
sub.dt2b[sub.dt2b$body_type=="self propelled caravan","body_type"] <- "rv/suv"
sub.dt2b[sub.dt2b$body_type=="sports car","body_type"] <- "coupe"

sub.dt2b[sub.dt2b$transmission_type=="continuously variable","transmission_type"] <- "automatic"

sub.dt2b$transmission_type <- ifelse(grepl("manual",sub.dt2b$transmission_type),"manual",
                                      ifelse(grepl("auto",sub.dt2b$transmission_type),"automatic",""))

head(sub.dt2b)
```
```{r}
GetSubmodel1 <- function(x,y=sub.dt2b){
  make = x[1]
  model = x[2]
  y_subset <- y[y[,1]==make & y[,2]==model,]
  #sub-model frequency table
  sub_table <- sort(-table(y_subset[,3]))
  sub_model = ifelse(names(sub_table[1])!="", names(sub_table[1]), names(sub_table[2]))
  return(sub_model)
  }
```
```{r}
sub.dt2ba<-sub.dt2b
sub.dt2c <- sub.dt2ba %>% select(make, model)
sub.dt_base1 <- unique(sub.dt2c)
system.time(
sub.dt2d <- sub.dt_base1 %>%
  mutate(Sub_model = apply(data.frame(make,model),1,GetSubmodel1))
)
```
```{r}
head(sub.dt2d,20)
```


```{r}
save(big_dt,sub.dt2d,file = "sim_new_mdata_10-5")
```

```{R}
fit_submodel <- function(x,y=sub.dt2d,meth='osa'){
  mak <- as.character(unlist(x[1]))
  mod <- as.character(unlist(x[2]))
  
  y_subset <- y[y[,1]==mak,]
  tol <-stringsim(mod,y_subset[,"model"],method=meth)
  
  max.fit <- which.max(tol)
  max.score <- tol[max.fit]
  
  if(length(max.fit)==0){
    final.tag <- 0
    score <- 0
  }else{
    a_make<- y_subset[max.fit,"make"]
    a_model <- y_subset[max.fit,"model"]
    a_sub <- y_subset[max.fit,"Sub_model"]
    final.tag <- which.max(y[,1]==a_make & y[,2]==a_model & y[,3]==a_sub)
    score <- max.score
    }
  
  return(list("fn_tag" = final.tag,"score" = score,"new_sub_model" = a_sub,"fit_make" = a_make, "fit_mod" = a_model))
}

gettag <- function(x,num){
  k <- unlist(x)[num]
  k
}

```
```{r}
tc<-new.df2

te1<- tc %>% select(r_id,finalmake,finalmodel,finalsubmodel,finalseats, finaltm, body_style) %>%
  mutate(
    fit_list = ifelse(finalsubmodel!="NONE","NOEMPTY",
      apply(data.frame(finalmake,finalmodel),1,fit_submodel,meth="jw")),
    score = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 2),1),
    fit_make = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 4),finalmake),
    fit_model = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 5),finalmodel),
    new_submodel = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 3),finalsubmodel))
```

```{r}
te1[te1$finalsubmodel=="NONE",][1:50,]
```
```{r}
dim(te1[te1$finalsubmodel=="NONE" |is.na(te1$finalsubmodel),])
dim(te1[(te1$finalsubmodel=="NONE"|is.na(te1$finalsubmodel)) & te1$score==1,])
dim(te1[(te1$finalsubmodel=="NONE"|is.na(te1$finalsubmodel)) & te1$score>=0.95,])
dim(te1[(te1$finalsubmodel=="NONE"|is.na(te1$finalsubmodel)) & te1$score>=0.9,])
dim(te1[(te1$finalsubmodel=="NONE"|is.na(te1$finalsubmodel)) & te1$score>=0.8,])
```
```{r}
dim(te1[te1$finalsubmodel=="NONE" ,])
dim(te1[(te1$finalsubmodel=="NONE") & te1$score==1,])
dim(te1[(te1$finalsubmodel=="NONE") & te1$score>=0.95,])
dim(te1[(te1$finalsubmodel=="NONE") & te1$score>=0.9,])
dim(te1[(te1$finalsubmodel=="NONE") & te1$score>=0.8,])
```

```{r}
te1[te1$finalsubmodel=="NONE" & te1$score>=0.95 & te1$score<1,][1:50,]
```

Model2: with highest frequency of 4 variables
```{r}
GetSubmodel2 <- function(x,y=sub.dt2b){
  make = x[1]
  model = x[2]
  body = x[3]
  trans = x[4]
  y_subset <- y[y[,1]==make & y[,2]==model & y[,4]==body & y[,5]==trans,]
  #sub-model frequency table
  sub_table <- sort(-table(y_subset[,3]))
  sub_model = ifelse(names(sub_table[1])!="", names(sub_table[1]), names(sub_table[2]))
  return(sub_model)
}

sub.dt2bb<-sub.dt2b
sub.dt2cb <- sub.dt2bb %>% select(make, model,transmission_type,body_type)
sub.dt_base2 <- unique(sub.dt2cb)
sub.dt2db <- sub.dt_base2 %>%
  mutate(Sub_model = apply(data.frame(make,model,body_type,transmission_type),1,GetSubmodel2))
```
```{r}
head(sub.dt2db)
```
```{R}
fit_submodel2 <- function(x,y=sub.dt2db,meth='osa'){
  mak <- as.character(unlist(x[1]))
  mod <- as.character(unlist(x[2]))
  body <- as.character(unlist(x[3]))
  trans <- as.character(unlist(x[4]))
  
  y_subset <- y[y[,1]==mak,]
  a <-stringsim(mod,y_subset[,"model"],method=meth)
  #if(trans!="NONE" | trans!=""){
  trans <- ifelse(trans=="NONE","",trans)
  b<-stringsim(trans,y_subset[,"transmission_type"],method=meth)
  #}else{
  #  b<-0
  #}
  
  c <- stringsim(body,y_subset[,"body_type"],method=meth)
  
  tol <- 0.6*a+0.2*b+0.2*c
  
  max.fit <- which.max(tol)
  max.score <- tol[max.fit]
  
  if(length(max.fit)==0){
    final.tag <- 0
    score <- 0
  }else{
    a_make<- y_subset[max.fit,"make"]
    a_model <- y_subset[max.fit,"model"]
    a_sub <- y_subset[max.fit,"Sub_model"]
    a_trans <- y_subset[max.fit,"transmission_type"]
    a_body <- y_subset[max.fit,"body_type"]
    final.tag <- which.max(y[,1]==a_make & y[,2]==a_model & y[,3]==a_sub & y[,4]==a_body & y[,5]==a_trans)
    score <- max.score
    }
  
  return(list("fn_tag" = final.tag,"score" = score,"new_sub_model" = a_sub,"fit_make" = a_make, "fit_mod" = a_model, "fit_body" = a_body, "fit_trans" = a_trans))
}

gettag <- function(x,num){
  k <- unlist(x)[num]
  k
}
```
```{R}
tc<-new.df2

te2<- tc %>% select(r_id,finalmake,finalmodel,finalsubmodel, body_style, finaltm) %>%
  mutate(
    fit_list = ifelse(finalsubmodel!="NONE","NOEMPTY",
      apply(data.frame(finalmake,finalmodel, body_style, finaltm),1,fit_submodel2,meth="jw")),
    score = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 2),1),
    fit_make = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 4),finalmake),
    fit_model = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 5),finalmodel),
    new_submodel = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 3),finalsubmodel),
    fit_body = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 6),body_style),
    fit_trans = ifelse(fit_list!="NOEMPTY",sapply(fit_list,gettag,num = 7),finaltm))
```

```{R}
head(te2[te2$finalsubmodel=="NONE",],20)
```
```{r}
dim(te2[te2$finalsubmodel=="NONE" |is.na(te2$finalsubmodel),])
dim(te2[(te2$finalsubmodel=="NONE"|is.na(te2$finalsubmodel)) & te2$score==1,])
dim(te2[(te2$finalsubmodel=="NONE"|is.na(te2$finalsubmodel)) & te2$score>=0.95,])
dim(te2[(te2$finalsubmodel=="NONE"|is.na(te2$finalsubmodel)) & te2$score>=0.9,])
dim(te2[(te2$finalsubmodel=="NONE"|is.na(te2$finalsubmodel)) & te2$score>=0.8,])

```

```{r}
te1_sub <- te1 %>% select(finalmake, finalmodel, finalsubmodel,fit_make,fit_model,new_submodel)
te2_sub <- te2 %>% select(fit_make,fit_model,new_submodel) %>%
  rename(new_submodel1 = new_submodel)
te_test <- cbind(te1_sub,te2_sub)
head(te_test)
```
```{r}
dim(te_test[te_test$new_submodel!=te_test$new_submodel1,])[1]

dim(te_test[te_test$new_submodel!=te_test$new_submodel1,])[1]/dim(te_test)[1]
```




```{r}
head(te1)
```
```{r}
te1$newsubmodel <- ifelse(te1$finalsubmodel=="NONE"  & te1$score==1,te1$new_submodel,te1$finalsubmodel)
```
```{r}
head(te1)
new.data1 <- te1 %>% select(r_id, finalmake, finalmodel, newsubmodel)
```
```{r}

col_name <- c("safety_rating","driversafetystars_n","year")
sub.dt2 <- full_data1a %>% select(r_id, col_name)
head(sub.dt2)
```

```{r}
dim(sub.dt2[sub.dt2$safety_rating=="NULL" | sub.dt2$safety_rating==0,])[1]/dim(sub.dt2)[1]
dim(sub.dt2[sub.dt2$driversafetystars_n=="NULL" | sub.dt2$driversafetystars_n==0,])[1]/dim(sub.dt2)[1]
```


```{r}
dcast(sub.dt2 , safety_rating~driversafetystars_n)
```
```{r}
sub.dt2$safety_star_fixed = ifelse(sub.dt2$driversafetystars_n!=0 & sub.dt2$driversafetystars_n!="NULL", sub.dt2$driversafetystars_n, ifelse(sub.dt2$safety_rating!="NULL" & sub.dt2$safety_rating!=0,sub.dt2$safety_rating,0))
```
```{r}
table(sub.dt2$driversafetystars_n)
table(sub.dt2$safety_star_fixed)
```
```{r}
save(sub.dt2,te1,te2,new.data1, file="safety_rate_data")
```
```{R}
load("safety_rate_data")
```

````{r}
sub.dt3 <- sub.dt2 %>%select(r_id, safety_star_fixed,year)
merg.dt<-merge(x=new.data1,y=sub.dt3,by="r_id",all.x=TRUE)
head(merg.dt,20)
```


```{r fig.width=15}
Check_safetey <- function(x,y){
  yrs = x
  y_subset <- y[y[,4]==yrs,]
  #safe star frequency table
  sub_table <- sort(-table(y_subset[,3]))
  new_safe = ifelse(names(sub_table[1])!=0, names(sub_table[1]), names(sub_table[2]))
  return(new_safe)
}

test_safe <- function(x,y=merg.dt){
  a <- y %>% select(finalmake, finalmodel, safety_star_fixed, year) %>%
  filter(finalmodel==x)
  b <- a %>% select(finalmake, finalmodel, year)
  c <- unique(b)
  ca <- c %>% mutate(new_safe = apply(data.frame(year),1,Check_safetey,y=a))
  cb <- ca %>% filter(!is.na(new_safe)) %>% mutate(new_safe = as.numeric(new_safe))
  d <- cb %>% ggplot(aes(x=year,y=new_safe)) + geom_point()  + labs(title=x) 
  return(d)
}

test_safe("corolla")
test_safe("swift")
test_safe("axela")
test_safe("commodore")
test_safe("hiace")
test_safe("hilux")
```

```{r fig.width=15}
test_safe1 <- function(x,y=merg.dt){
  a <- y %>% select(finalmake, finalmodel, safety_star_fixed, year) %>%
  filter(finalmodel==x & as.numeric(safety_star_fixed)!=0 ) %>%
    mutate(year_group = ifelse(year>2010,"2011-2020",ifelse(year>2000,"2001-2010",ifelse(year>1990,"1991-2000",
                            ifelse(year>1980,"1981-1990", ifelse(year>=1971,"1971-1980","1900-1970"))))))
  
  d <- a %>% ggplot(aes(x=year_group,y=as.numeric(safety_star_fixed),fill=year_group)) + geom_violin(scale = "width")   + scale_fill_brewer(palette="Blues") + theme_minimal()+ labs(title=x) + stat_summary(fun.y = "median", geom="point", shape=16, size=2, col = "red") + theme(legend.position = "none") 
  return(d)
}

test_safe1("corolla")
test_safe1("swift")
test_safe1("axela")
test_safe1("commodore")
test_safe1("hiace")
test_safe1("hilux")
```

```{r}
Check_empty_plot <- function(dt,col_name,target){
  sub_empty_dt <- dt %>% select(col_name,target) %>% filter((!!sym(target))==0 |(!!sym(target))=="NULL" | is.na(!!sym(target)))
  emt_sort <- -sort(-table(sub_empty_dt[,col_name]))[1:15]
  emt_sort2<-as.data.frame(emt_sort)
  emt_sort2 %>% ggplot(aes(x=Var1,y=Freq)) + geom_histogram(stat='identity')
}
Check_empty_plot(dt=merg.dt,col_name = "finalmodel",target="safety_star_fixed")
Check_empty_plot(dt=merg.dt,col_name = "year",target="safety_star_fixed")
Check_empty_plot(dt=merg.dt,col_name = "finalmake",target="safety_star_fixed")
```



```{R fig.width=15}
test_safe3 <- function(x,y=merg.dt){
  a <- y %>% select(finalmake, finalmodel, safety_star_fixed, year) %>% filter(finalmodel==x & as.numeric(safety_star_fixed)!=0 ) %>%
      mutate(year_group = ifelse(year>2010,"2011-2020",ifelse(year>2000,"2001-2010",ifelse(year>1990,"1991-2000",ifelse(year>1980,"1981-1990",    ifelse(year>=1971,"1971-1980","1900-1970"))))),
            safety_star_fixed = as.numeric(safety_star_fixed) )
    
  b <- a %>% select(finalmake, finalmodel, year)
  c <- unique(b)
  ca <- c %>% mutate(new_safe = as.numeric(apply(data.frame(year),1,Check_safetey,y=a))) %>% select(year,new_safe)
  
  new_merg<-merge(x=a,y=ca,by="year",all.x=TRUE)  
    
  p <- new_merg %>% ggplot() + geom_point(aes(x=year,y=new_safe)) 
  
  p <- p + geom_violin(aes(x=year_group,y=as.numeric(safety_star_fixed),fill=year_group), scale = "width")   + scale_fill_brewer(palette="Blues") + theme_minimal() + theme(legend.position = "none") + theme(legend.position = "none") 
  return(p)
}

test_safe3("corolla")
```

```{R}
Check_safetey2 <- function(x,y){
  yrs = x[1]
  mak = x[2]
  mod = x[3]
  y_subset <- y[y[,4]==yrs & y[,1]==mak & y[,2]==mod,]
  #safe star frequency table
  sub_table <- sort(-table(y_subset[,3]))
  new_safe = ifelse(names(sub_table[1])!=0, names(sub_table[1]), ifelse(names(sub_table[2])!=0,names(sub_table[2]),0))
  return(new_safe)
}

subset_rate_dt <- merg.dt %>% select( finalmake, finalmodel, safety_star_fixed, year, r_id) 
subset_rate_dt2 <- subset_rate_dt %>% filter(as.numeric(safety_star_fixed)!=0 ) %>% select(finalmake, finalmodel, year)
subset_rate_dt_uni <- unique(subset_rate_dt2)
rate_merge_dt <- subset_rate_dt_uni %>% mutate(new_safe = as.numeric(apply(data.frame(year,finalmake, finalmodel),1,Check_safetey2,y=subset_rate_dt))) 

new_star_merge_dt<-merge(x=subset_rate_dt,y=rate_merge_dt,by=c("year","finalmake","finalmodel"),all.x=TRUE)
    

Check_safetey3 <- function(x,y){
  mak = x[1]
  mod = x[2]
  y_subset <- y[ y[,1]==mak & y[,2]==mod,]
  #safe star frequency table
  sub_table <- sort(-table(y_subset[,3]))
  new_safe = ifelse(names(sub_table[1])!=0, names(sub_table[1]), ifelse(names(sub_table[2])!=0,names(sub_table[2]),0))
  return(new_safe)
}
subset_rate_dt3 <- subset_rate_dt %>% filter(as.numeric(safety_star_fixed)!=0 ) %>% select(finalmake, finalmodel)
subset_rate_dt_uni_noyear <- unique(subset_rate_dt3)
subset_rate_dt_uni_noyear <- subset_rate_dt_uni_noyear %>% mutate(new_safe_all = as.numeric(apply(data.frame(finalmake, finalmodel),1,Check_safetey3,y=subset_rate_dt))) 

new_star_merge_dt<-merge(x=new_star_merge_dt,y=subset_rate_dt_uni_noyear,by=c("finalmake","finalmodel"),all.x=TRUE)
head(new_star_merge_dt)
```
```{R}
dim(new_star_merge_dt[new_star_merge_dt$safety_star_fixed==0,])
dim(new_star_merge_dt[is.na(new_star_merge_dt$new_safe),])[1]/dim(new_star_merge_dt)[1]
dim(new_star_merge_dt[new_star_merge_dt$safety_star_fixed==0,])[1]/dim(new_star_merge_dt)[1]
# The percentage of missing value only fixed by same make, model and year
dim(new_star_merge_dt[new_star_merge_dt$safety_star_fixed==0 & !is.na(new_star_merge_dt$new_safe),])[1]/dim(new_star_merge_dt)[1]
# The percentage of missing value fixed by same make, model as well
dim(new_star_merge_dt[new_star_merge_dt$safety_star_fixed==0 & !is.na(new_star_merge_dt$new_safe_all),])[1]/dim(new_star_merge_dt)[1]
```

```{R}
new_star_merge_dt2 <- new_star_merge_dt %>% select(r_id,finalmake, finalmodel, year, new_safe_all) %>%
  rename(new_safety_rating=new_safe_all)
head(new_star_merge_dt2)
```
```{R}
sub_dt1 <- new.data1 %>%select(r_id, newsubmodel)
new_star_merge_dt3 <- merge(x=new_star_merge_dt2,y=sub_dt1,by=c("r_id"),all.x=TRUE)
new_star_merge_dt3 <- new_star_merge_dt3%>%select(r_id, finalmake,finalmodel, newsubmodel,year,new_safety_rating)
head(new_star_merge_dt3)
```
```{R}
save(new_star_merge_dt3, file = "new_star_merge_dt")
```


######################################################################################################
Engine size
```{r}
engine_dt <- full_data1a %>% select(r_id,engine_size,enginesize_n) %>%
  mutate(engine1 = ifelse(engine_size!="NULL",engine_size,ifelse(enginesize_n!="NULL",enginesize_n,0)))
dim(engine_dt[engine_dt$engine_size=="NULL",])
dim(engine_dt[engine_dt$enginesize_n=="NULL",])
dim(engine_dt[engine_dt$engine1==0,])
head(engine_dt)
engine_dt2 <- engine_dt %>%select(r_id,engine1) %>% mutate(engine1 = as.numeric(engine1))
engine_merge <- merge(x = new_star_merge_dt3,y=engine_dt2,by="r_id",all.x = TRUE)
head(engine_merge)
```
```{R fig.width=10}
engine_plot <- function(x,y = engine_merge){
  y_sub <- y[y$finalmodel==x,]
  p <- y_sub %>% ggplot(aes(x=factor(year),y=engine1)) + geom_point() + scale_fill_gradient(low="lightblue1",high="darkblue",trans="log10")
  p
}
engine_plot("corolla")
engine_plot("swift")
engine_plot("axela")
engine_plot("commodore")
engine_plot("hiace")
engine_plot("hilux")
```
check engine missing distribution
```{r}
Check_empty_plot <- function(dt,col_name,target){
  sub_empty_dt <- dt %>% select(col_name,target) %>% filter((!!sym(target))==0 |(!!sym(target))=="NULL" | is.na(!!sym(target)))
  emt_sort <- -sort(-table(sub_empty_dt[,col_name]))[1:15]
  emt_sort2<-as.data.frame(emt_sort)
  emt_sort2 %>% ggplot(aes(x=Var1,y=Freq)) + geom_histogram(stat='identity') + ylab(paste0(target,"_Freq")) + xlab(col_name)
}
Check_empty_plot(dt=engine_merge,col_name = "finalmodel",target="engine1")
Check_empty_plot(dt=engine_merge,col_name = "year",target="engine1")
Check_empty_plot(dt=engine_merge,col_name = "finalmake",target="engine1")
```
```{R}
dim(engine_merge[engine_merge$engine1==0,])
```
```{r}
fit_rest_variable <- function(x,y,meth='osa'){
  mak <- as.character(unlist(x[1]))
  mod <- as.character(unlist(x[2]))
  s_mod <- as.character(unlist(x[3]))
  y <- as.data.frame(y)
  y_sub <- y[y[,2]==mak,]
  a<-stringsim(mod,y_sub[,"finalmodel"],method=meth)

  if(!is.na(s_mod)){
    b<-stringsim(s_mod,y_sub[,"newsubmodel"],method=meth)
  }else{
    b<-0
  }
  
  tol<- 0.6*a+0.4*b
  
  max.fit <- which.max(tol)
  max.score <- tol[max.fit]
  mod.score <- a[max.fit]
  smod.score <- b[max.fit]
  
  if(length(max.fit)==0){
    final.tag <- 0
    score <- 0
  }else{
    final.tag <- y_sub[max.fit,"r_id"]
    score <- max.score
    }
  #return(final.tag) 
  return(list("fn_tag" = final.tag,"score" = score)) 
}

Get_from_model <- function(me.dt,col_name,score=0.8){
  
  me.dt[,col_name] <- ifelse((me.dt[,col_name]==0|me.dt[,col_name]=="NULL"|me.dt[,col_name]=="N/A"),"",me.dt[,col_name])
  
  col <- col_name
  
  sub.dt.noempty <- me.dt  %>% filter((!!sym(col))!="")
  sub.dt.noempty2 <- sub.dt.noempty %>% select(r_id,finalmake,finalmodel,newsubmodel,(!!sym(col))) %>% group_by(finalmake,finalmodel,newsubmodel,(!!sym(col))) %>% slice(1)
  
  new_merg.dt <- me.dt %>% mutate(
  new_tag = ifelse((!!sym(col))!="", r_id, apply(data.frame(finalmake,finalmodel,newsubmodel,col_name), 1, fit_rest_variable, y=sub.dt.noempty2, meth="jw")),
    score = ifelse((!!sym(col))!="", 1, sapply(new_tag,gettag,num = 2)),
    fn_tag = ifelse((!!sym(col))!="", r_id, sapply(new_tag,gettag,num = 1))
)
  
  sub.dt.noempty3 <- as.data.frame(sub.dt.noempty2) %>% select(r_id,col_name)
  
  new_merg.dt2 <- new_merg.dt %>% left_join(sub.dt.noempty3, by = c("fn_tag" = "r_id"))

  new_merg.dt2[,paste0("new_",col_name)] <- ifelse(new_merg.dt2[,"score"] >= score & new_merg.dt2[,paste0(col_name,".x")]=="", new_merg.dt2[,paste0(col_name,".y")],new_merg.dt2[,paste0(col_name,".x")])
  
  
  new_merg.dt3 <- new_merg.dt2 %>% select(r_id,paste0("new_",col_name))
  final.dt<-merge(x=me.dt,y=new_merg.dt3,by="r_id",all.x=TRUE)
  
  return(final.dt)
}
engine_merge_dt1<-Get_from_model(me.dt = engine_merge, col_name="engine1")
head(engine_merge_dt1)
```
```{r}
engine_merge_dt1[engine_merge_dt1$engine1=="",][1:10,]
engine_merge_dt2 <- engine_merge_dt1 %>% select(r_id,finalmake,finalmodel,newsubmodel,year,new_safety_rating,new_engine1) %>%
  rename(new_engine_size=new_engine1 )
```

```{r}
dim(engine_merge_dt1[engine_merge_dt1$engine1=="",])[1]
dim(engine_merge_dt1[engine_merge_dt1$new_engine1=="",])[1]
```



######################################################################################################
fuel_economy_stars
```{r}
economy_dt <- full_data1a %>% select(r_id,model, year, fuel_economy_stars)
-sort(-table(economy_dt$fuel_economy_stars))
```

```{R}
Check_variable <- function(x,y){
  yrs = x
  y_subset <- y[y[,3]==yrs,]
  #safe star frequency table
  sub_table <- sort(-table(y_subset[,2]))
  new_safe = ifelse(names(sub_table[1])!=0, names(sub_table[1]), names(sub_table[2]))
  return(new_safe)
}

test_variable <- function(x,y=economy_dt,var){
  a <- y %>% select(model, var, year) %>%
  filter(model==x)
  b <- a %>% select(model, year)
  c <- unique(b)
  ca <- c %>% mutate(new_variable = apply(data.frame(year),1,Check_variable,y=a))
  cb <- ca %>% filter(!is.na(new_variable)) %>% mutate(new_variable = as.numeric(new_variable)) %>% filter(!is.na(new_variable))
  d <- cb %>% ggplot(aes(x=year,y=new_variable)) + geom_point()  + labs(title=x) + ylab(var)
  return(d)
}
test_variable("Corolla",y=economy_dt,var="fuel_economy_stars")
test_variable("Swift",y=economy_dt,var="fuel_economy_stars")
test_variable("Axela",y=economy_dt,var="fuel_economy_stars")
test_variable("Commodore",y=economy_dt,var="fuel_economy_stars")
test_variable("Hiace",y=economy_dt,var="fuel_economy_stars")
test_variable("Hilux",y=economy_dt,var="fuel_economy_stars")
```
```{R}
Check_empty_plot(dt=economy_dt,col_name = "model",target="fuel_economy_stars")
Check_empty_plot(dt=economy_dt,col_name = "year",target="fuel_economy_stars")
```


####################################################################################################################
Weight and weight_n

```{R}
weight_dt <- full_data1a %>% select(r_id,model, year, weight_n)
-sort(-table(weight_dt$weight_n))[1:20]
print("===================")
weight_dt$weight_n <- ifelse(weight_dt$weight_n=="NULL",0,weight_dt$weight_n)
-sort(-table(weight_dt$weight_n))[1:20]
```

```{r fig.width=10}
test_variable("Corolla",y=weight_dt,var="weight_n")
test_variable("Swift",y=weight_dt,var="weight_n")
test_variable("Axela",y=weight_dt,var="weight_n")
test_variable("Commodore",y=weight_dt,var="weight_n")
test_variable("Hiace",y=weight_dt,var="weight_n")
test_variable("Hilux",y=weight_dt,var="weight_n")
```

```{R}
Check_empty_plot(dt=weight_dt,col_name = "model",target="weight_n")
Check_empty_plot(dt=weight_dt,col_name = "year",target="weight_n")
```







